patsy/build.py, patsy/categorical.py, patsy/contrasts.py, patsy/design_info.py, patsy/state.py, patsy/test_highlevel.py, patsy/util.py
Okay, here's my attempt to work around the changes in categorical handling in pandas 0.15.
@JanSchulz: I would very much appreciate a review, since this is heavily based on your patch in #47 (plus some refactoring to try and fix a few more issues). The individual commits are logical chunks, so it might be easier to read that way then as one giant patch.
I'd also really appreciate if you could write down a self-contained test that triggers the issue in pydata/pandas#9581, or at least enough of an example to let me trigger it? I'm pretty sure I fixed it, but I'm not sure how to write a test case for it...
@kousu: I don't fully understand the issues you described in https://github.com/pydata/patsy/pull/47#issuecomment-72605624 , so I'm not sure whether I've fixed them or not :-). (They did …
=> Pandas 0.15 categorical handling

doc/changes.rst, doc/expert-model-specification.rst, doc/formulas.rst, patsy/build.py, patsy/desc.py, patsy/eval.py, patsy/highlevel.py, patsy/test_build.py, patsy/test_highlevel.py, patsy/user_util.py
This is the current state of my work  to capture only the required variables for patsy formulas instead of the whole environment.
Current status: 
When this is complete, it will fix bug #25.
=> Capture vars not env

patsy/eval.py
Fixes the example as show [here](http://patsy.readthedocs.org/en/latest/API-reference.html#patsy.EvalEnvironment.capture).
=> [doc] How to access the EvalEnviroment namespace

doc/changes.rst, doc/py2-versus-py3.rst, patsy/highlevel.py, patsy/test_highlevel.py
Apparently our disallowing unicode formula strings on Py2 was being
rather annoying for people using `from __future__ import
unicode_literals`. Start allowing them in limited circumstances.
Fixes gh-53.
=> Allow unicode formulas on Py2 in limited circumstances.

patsy/design_info.py
Discovered by @rsgmon in gh-82.
=> Fix a crash in DesignMatrix.__repr__ when shape[0] == 0

.travis.yml, patsy/categorical.py, patsy/test_build.py, patsy/test_highlevel.py, patsy/util.py
I'm not sure what version this changed in, but originally the only way
to get is_categorical_dtype was as a private export from
pandas.core.common. Now that's deprecated, and you're supposed to get it
from pandas.api.type. We try both, to cover both periods.
=> Adapt to new location of pandas is_categorical_dtype

patsy/tokens.py
https://github.com/python/cpython/commit/c4ef4896eac86a6759901c8546e26de4695a1389
(not yet in any released version, but it's been backported to all
versions of Python in git, even 2.7!) changed the behaviour in the
stdlib's tokenize module to emit a synthetic NEWLINE token even if the
file does not end with a newline. This was causing a spurious
"mixed-line-endings" warning to be emitted, but luckily the synthetic
token is easy to test for (the token text is "").
=> fix compatibility with unreleased changes to stdlib tokenizer

.travis.yml, patsy/constraint.py, patsy/util.py
Here's a way to fix travis. 
There's a conda dependency problem that can be easily solved by building the conda environment with only one `conda install`. 
`numpy.testing.util` is deprecated as well, so I did a `try/except` to use the newer one, if available. 
One concern is that numpy is deprecating `np.matrix`. 
```
======================================================================
ERROR: patsy.util.test_atleast_2d_column_default
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/miniconda/envs/testenv/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/travis/miniconda/envs/testenv/lib/python3.6/site-packages/patsy/util.py", line 176, in …
```
=> MAINT: Travis fixes

README.rst
This link in the README.rst goes nowhere.
=> MAINT: Remove dead link

README.rst, doc/changes.rst, release-checklist.txt
Just link to the (new!) overview DOI instead of manually adding links
to each release's DOI.
=> Rework zenodo handling to make releasing simpler

.travis.yml, patsy/constraint.py, tools/check-API-refs.py
I think this will get python 3.7 testing on patsy
=> TST: Add python 3.7 testing

doc/expert-model-specification.rst, doc/quickstart.rst, patsy/splines.py, patsy/state.py, patsy/util.py
There are small typos in:
- doc/expert-model-specification.rst
- doc/quickstart.rst
- patsy/splines.py
- patsy/state.py
- patsy/util.py
Fixes:
- Should read `heterogeneous` rather than `heterogenous`.
- Should read `specified` rather than `specificed`.
- Should read `representation` rather than `represention`.
- Should read `concatenation` rather than `concatentation`.
Closes #172
=> docs: fix a few simple typos

.github/workflows/tox.yml, setup.py, tox.ini
Until we formally deprecate python 2.7 let's keep it in the build matrix.
=> Add py27 and py39 to build matrix.

patsy/eval.py
Fixes #186 by handling future features where the mandatory release version is `None`, indicating the feature was dropped. These are now included in `patsy.eval._ALL_FUTURE_FLAGS` rather than causing a `TypeError`.
The first appearance of such a feature is in Python 3.11, in which `__future__.annotations.getMandatoryRelease()` returns `None`.
=> Handle dropped future features

.github/workflows/tox.yml, patsy/parse_formula.py, patsy/tokens.py, setup.py, tox.ini
=> Add support for Python 3.12 (and adjust code for tokenizer changes).

.github/workflows/tox.yml, doc/stateful-transforms.rst, patsy/constraint.py, patsy/state.py, patsy/test_state.py
row_stack is official deprecated in NumPy 2, and will be dropped eventually.  Currently produces a warning
=> MAINT: Repalce row_stack with vstack

patsy/util.py
This patch side-steps the issues addressed by #198 and #199, but avoiding recently deprecated APIs.
=> Avoid deprecated pandas `is_categorical_dtype` API

patsy/util.py
fixes https://github.com/pydata/patsy/issues/210
see more information
https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
related to https://github.com/scipy/scipy/pull/20172
=> MAINT: add support for numpy2

.github/workflows/tox.yml, patsy/eval.py, tox.ini
Where possible we will now use `setup-python`; only using `pyenv` where necessary for older Python versions.
=> Migrate to `setup-python` in GitHub Actions (and enable 3.13 tox builds).

patsy/eval.py, tox.ini
Move import to within the test function and change skip method
closes #215
=> BUG: Remove pytest import from top of module

doc/changes.rst, patsy/version.py
Increment version from 1.0.0 to 1.0.1
Add release note
=> RLS: Prepare patsy 1.0.1
